# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e224d68e9a4e3a770625b6f2eed962ae95ffd5c850e31f5005d75ad224c5141cf336847d6a8446fcf9e6011610c2c7c77902a1535c1ca07ff8e796df73eb742d

test:
  secret_key_base: b56899f8faff82cdbc47014844544787878a83adad1700ccaf7801ecceffb112e6de8957a89a6207f181ff25dadfe5a917c5c30834d512f7e254326c80c18298

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
